import Head from "next/head";
import rocket from "public/lotties/rocket.json";
import { PostCard } from "~/components/Post";
import { ArrowRightIcon } from "@heroicons/react/24/outline";
import Link from "next/link";
import React from "react";
import { useState } from "react";
import dynamic from "next/dynamic";
import { findPosts } from '../utils/api.js';
const Lottie = dynamic(() => import("react-lottie"), { ssr: false });

export type Post = {
  id: Number;
  title: string;
  body: string;
  author: string;
  datePublished: Date;
  dateLastModified: Date;
  impact: number;
  views: number;
  tags: string[];
  communityForum: Comment[];
  professionalForum: Comment[];
};

export type Comment = {
  text: string;
  author: string;
  datePosted: Date;
};

var posts = await findPosts("title");
var postsData = posts.data.data;

const mockPosts: Post[] = []

for (var i = 0; i < posts.data.data.length; i++)
{
  var postData = postsData[i];

  mockPosts.push(
    {
        id: i,
        title: postData.title,
        body: postData.body,
        author: postData.author,
        datePublished: postData.datePublished,
        dateLastModified: postData.dateLastModified,
        impact: postData.impact,
        views: postData.views,
        tags: postData.tags,
        communityForum: [],
        professionalForum: [],
      }
  );
}

export default function Home() {
  const [hoverPostId, setHoverPostId] = useState<string>("");

  return (
    <>
      <Head>
        <title>Pseudo</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/icons/code.svg" />
      </Head>
      <div className="grid w-full grid-cols-12 gap-4">
        <div className="col-span-12 overflow-hidden rounded-lg border border-gray-200 shadow-sm">
          <div className="space overflow-hidden">
            <div id="stars"></div>
            <div id="stars2"></div>
            <div id="stars3"></div>
            <div className="shootingstar"></div>
            <div className="shootingstar"></div>
            <div className="shootingstar"></div>
            <div className="shootingstar"></div>
            <div className="shootingstar"></div>
            <h2 id="title" className="text-lg font-semibold">
              Welcome to Pseudo!
            </h2>
            <p id="subtitle" className="text-lg font-semibold">
              Auburn Hacks 2024!
            </p>
            <div className="rotate-45">
              <Lottie
                options={{
                  loop: true,
                  autoplay: true,
                  animationData: rocket,
                  rendererSettings: {
                    preserveAspectRatio: "xMidYMid slice",
                  },
                }}
                height={150}
                width={150}
              />
            </div>
          </div>
        </div>
        <div className="col-span-8 flex flex-col items-center gap-2">
          <div className="w-full rounded-lg border border-gray-200 bg-white px-6 py-4 shadow-sm">
            <h2 className="text-xl font-semibold">Top Questions</h2>
            <div className="flex flex-col divide-y-2">
              {mockPosts.map((post, idx) => (
                <PostCard
                  key={idx}
                  data={post}
                  hoverId={hoverPostId}
                  setHoverId={setHoverPostId}
                />
              ))}
            </div>
          </div>
          <Link
            href="/questions"
            className="border-primaryGreen-900 flex items-center gap-2 rounded-lg border bg-primaryGreen px-8 py-2 text-white shadow-sm"
          >
            <div>See more</div>
            <ArrowRightIcon className="h-4 w-4" />
          </Link>
        </div>
        <div className="col-span-4 flex flex-col items-center">
          <div className="w-full rounded-lg border border-gray-200 bg-white px-6 py-4 shadow-sm">
            <h2 className="text-xl font-semibold">Platform Stats</h2>
          </div>
        </div>
      </div>
    </>
  );
}

// Keep incase we need to later  referendce to implement the user profile fetch.
//
// import React from "react";
// import { useUser } from "@auth0/nextjs-auth0/client";

// function index() {
//   const { user, error, isLoading } = useUser();
//   return <a href="api/auth/login">Login</a>;
// }

// export default index;
