import Head from "next/head";
import React from "react";

export default function Home() {
  return (
    <>
      <Head>
        <title>Pseudo</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/icons/code.svg" />
      </Head>
      <div className="grid w-full grid-cols-12 gap-4">
        <div className="col-span-8 rounded-lg border border-gray-200 bg-white px-6 py-2 shadow-sm">
          <h2 className="text-lg font-semibold">Top Questions</h2>
        </div>
        <div className="col-span-4 rounded-lg border border-gray-200 bg-white px-6 py-2 shadow-sm"></div>
      </div>
    </>
  );
}

// Keep incase we need to later  referendce to implement the user profile fetch.
//
// import React from "react";
// import { useUser } from "@auth0/nextjs-auth0/client";

// function index() {
//   const { user, error, isLoading } = useUser();
//   return <a href="api/auth/login">Login</a>;
// }

// export default index;
